# Generated by Django 4.1.6 on 2023-03-19 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cabain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabain_name', models.CharField(max_length=100)),
                ('cabain_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('minimal_age', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(16)])),
                ('maximum_age', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(16)])),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camper_name', models.CharField(max_length=40)),
                ('camper_age', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
                ('cabain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cabain')),
            ],
        ),
        migrations.AddField(
            model_name='cabain',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.village'),
        ),
    ]
