# Generated by Django 4.1.6 on 2023-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_camper_camper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='camper_preference_1',
            field=models.CharField(choices=[('1', 'Ropes'), ('2', 'HBR'), ('3', 'Soccer'), ('4', 'Pottery'), ('5', 'Arts'), ('6', 'Archery')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='camper',
            name='camper_preference_2',
            field=models.CharField(choices=[('1', 'Ropes'), ('2', 'HBR'), ('3', 'Soccer'), ('4', 'Pottery'), ('5', 'Arts'), ('6', 'Archery')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='camper',
            name='camper_preference_3',
            field=models.CharField(choices=[('1', 'Ropes'), ('2', 'HBR'), ('3', 'Soccer'), ('4', 'Pottery'), ('5', 'Arts'), ('6', 'Archery')], default='1', max_length=50),
        ),
    ]
