# Generated by Django 4.1.6 on 2023-03-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_camper_camper_preference_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='camper_preference_1',
            field=models.CharField(default='Ropes', max_length=50),
        ),
        migrations.AlterField(
            model_name='camper',
            name='camper_preference_2',
            field=models.CharField(default='Ropes', max_length=50),
        ),
        migrations.AlterField(
            model_name='camper',
            name='camper_preference_3',
            field=models.CharField(default='Ropes', max_length=50),
        ),
    ]
