# Generated by Django 4.1.6 on 2023-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_camper_camper_preference_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='camper_preference_4',
            field=models.CharField(default='Ropes', max_length=50),
        ),
    ]
